[build]
builder = "nixpacks"
buildCommand = "composer install"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["php81", "php81Extensions.sqlite3"]

[env]
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/data/database.sqlite" 