[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["php81", "php81Extensions.sqlite3", "php81Extensions.pdo", "php81Extensions.pdo_sqlite", "php81Extensions.ctype", "php81Extensions.iconv", "php81Extensions.mbstring", "php81Extensions.xml", "php81Extensions.bcmath", "php81Extensions.json", "php81Extensions.openssl", "php81Extensions.tokenizer", "php81Extensions.filter", "php81Extensions.session", "php81Extensions.dom", "php81Extensions.libxml", "php81Extensions.simplexml"]

[env]
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/data/database.sqlite" 