<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SeriesController extends Controller
{
    /**
     * Obtiene los datos de las series desde un array estático
     * En una aplicación real, estos datos vendrían de una base de datos
     */
    private function getSeriesData()
    {
        $series = [
            [
                'id' => 1,
                'title' => 'Juego de Tronos',
                'description' => 'Nueve familias nobles luchan por el control de las tierras de Poniente, mientras un antiguo enemigo regresa tras haber estado inactivo durante milenios.',
                'genre' => 'Action, Adventure, Drama, Fantasy, Mystery, Sci-Fi',
                'release_year' => 2011,
                'seasons' => 8,
                'rating' => 9.2,
                'image_url' => 'https://i.pinimg.com/736x/a9/ee/15/a9ee15e120c5fcd6fbcf87b8c38dcb6f.jpg',
            ],
            [
                'id' => 2,
                'title' => 'Breaking Bad',
                'description' => 'Un profesor de química diagnosticado con cáncer de pulmón inoperable comienza a fabricar y vender metanfetamina con un antiguo alumno para asegurar el futuro de su familia.',
                'genre' => 'Crime, Drama, Thriller',
                'release_year' => 2008,
                'seasons' => 5,
                'rating' => 9.5,
                'image_url' => 'https://i.pinimg.com/736x/f5/99/33/f59933a500f42170330f05116ad0fe1b.jpg',
            ],
            [
                'id' => 3,
                'title' => 'The Last of Us',
                'description' => 'Después de que una pandemia global destruye la civilización, un superviviente endurecido se hace cargo de una niña de 14 años que puede ser la última esperanza de la humanidad.',
                'genre' => 'Action, Adventure, Drama, Horror, Sci-Fi, Thriller',
                'release_year' => 2023,
                'seasons' => 2,
                'rating' => 8.6,
                'image_url' => 'https://i.blogs.es/fe179c/the-last-of-us-intro-serie-hbo-max/1366_2000.jpeg',
            ],
            [
                'id' => 4,
                'title' => 'Stranger Things',
                'description' => 'Cuando un joven desaparece, un pequeño pueblo descubre un misterio que involucra experimentos secretos, fuerzas sobrenaturales aterradoras y una extraña niña.',
                'genre' => 'Drama, Fantasy, Horror, Mystery, Sci-Fi, Thriller',
                'release_year' => 2016,
                'seasons' => 5,
                'rating' => 8.6,
                'image_url' => 'https://pyramidinternational.com/cdn/shop/files/wdc101200_9e23987a-8bb7-4ca6-bf64-c25aaa4f4db7.jpg?v=1738716526',
            ],
             [
                'id' => 5,
                'title' => 'The Walking Dead',
                'description' => 'El ayudante del sheriff Rick Grimes se despierta de un coma para descubrir que el mundo está en ruinas y debe liderar a un grupo de supervivientes para mantenerse con vida.',
                'genre' => 'Drama, Horror, Thriller',
                'release_year' => 2010,
                'seasons' => 11,
                'rating' => 8.1,
                'image_url' => 'https://logowik.com/content/uploads/images/the-walking-dead-tv-series5057.logowik.com.webp',
            ],
            [
                'id' => 6,
                'title' => 'Los Soprano',
                'description' => 'El jefe de la mafia de Nueva Jersey, Tony Soprano, lidia con problemas personales y profesionales en su hogar y en su vida empresarial, que afectan su estado mental y a su familia.',
                'genre' => 'Crime, Drama',
                'release_year' => 1999,
                'seasons' => 6,
                'rating' => 9.2,
                'image_url' => 'https://shop.hbo.com/cdn/shop/files/SOPR-25-85-101009-RO_4934c5e2-63b1-4ae7-8db7-bf78e56d673f_1080x.jpg?v=1704301173',
            ],
            [
                'id' => 7,
                'title' => 'The Wire',
                'description' => 'El mundo de las drogas de Baltimore, visto a través de los ojos de traficantes y agentes de la ley.',
                'genre' => 'Crime, Drama, Thriller',
                'release_year' => 2002,
                'seasons' => 5,
                'rating' => 9.3,
                'image_url' => 'https://shop.hbo.com/cdn/shop/products/WIRE-LOGO-White-100011-RO_1080x.png?v=1626201030',
            ],
            [
                'id' => 8,
                'title' => 'Friends',
                'description' => 'Sigue las vidas personales y profesionales de seis amigos de entre veinte y treinta y tantos años que viven en el distrito de Manhattan en la ciudad de Nueva York.',
                'genre' => 'Comedy, Romance',
                'release_year' => 1994,
                'seasons' => 10,
                'rating' => 8.9,
                'image_url' => 'https://assets.turbologo.com/blog/es/2019/12/19132808/friends-logo-cover-958x575.png',
            ],
             [
                'id' => 9,
                'title' => 'Chernobyl',
                'description' => 'En abril de 1986, una explosión en la central nuclear de Chernobyl en la Unión de Repúblicas Socialistas Soviéticas se convierte en una de las peores catástrofes provocadas por el hombre en el mundo.',
                'genre' => 'Drama, History, Thriller',
                'release_year' => 2019,
                'seasons' => 1,
                'rating' => 9.3,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ32XPa08uRlnlN0bP3961tZbNbkwZMUg1_g&s',
            ],
            [
                'id' => 10,
                'title' => 'The Crown',
                'description' => 'Sigue las rivalidades políticas y el romance del reinado de la Reina Isabel II y los eventos que marcaron la segunda mitad del siglo XX.',
                'genre' => 'Biography, Drama, History',
                'release_year' => 2016,
                'seasons' => 6,
                'rating' => 8.0,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/The_crown_logo2.png/1280px-The_crown_logo2.png',
            ],
             [
                'id' => 11,
                'title' => 'Black Mirror',
                'description' => 'Una serie de antología que explora un futuro cercano retorcido y de alta tecnología donde chocan las mayores innovaciones de la humanidad y sus instintos más oscuros.',
                'genre' => 'Drama, Sci-Fi, Thriller',
                'release_year' => 2011,
                'seasons' => 6,
                'rating' => 8.7,
                'image_url' => 'https://m.media-amazon.com/images/M/MV5BMGRjZDBjODMtMWQ1Zi00MWRkLTk5YTMtMDU1NTNkMzhkM2QwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
            ],
            [
                'id' => 12,
                'title' => 'The Mandalorian',
                'description' => 'Los viajes de un cazarrecompensas solitario en los confines de la galaxia, lejos de la autoridad de la Nueva República.',
                'genre' => 'Action, Adventure, Fantasy, Sci-Fi',
                'release_year' => 2019,
                'seasons' => 3,
                'rating' => 8.7,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrKdhT7BfxFQyUUki6_kBcxUG1cez0-iJzeA&s',
            ],
             [
                'id' => 13,
                'title' => 'The Boys',
                'description' => 'Un grupo de vigilantes conocidos como The Boys se propone acabar con superhéroes corruptos que abusan de sus superpoderes.',
                'genre' => 'Action, Comedy, Crime, Drama, Sci-Fi',
                'release_year' => 2019,
                'seasons' => 4,
                'rating' => 8.7,
                'image_url' => 'https://m.media-amazon.com/images/S/pv-target-images/88a0f6bf4f033bc2fe2e35d0b08b022abf3da66766580dcbc863bb4ca725a740.jpg',
            ],
            [
                'id' => 14,
                'title' => 'Loki',
                'description' => 'El voluble villano Loki (Tom Hiddleston) retoma su papel como el Dios de las Travesuras en una nueva serie que tiene lugar después de los eventos de "Avengers: Endgame".',
                'genre' => 'Action, Adventure, Fantasy, Sci-Fi',
                'release_year' => 2021,
                'seasons' => 2,
                'rating' => 8.2,
                'image_url' => 'https://i.pinimg.com/736x/ca/57/7b/ca577bb262da9f86d54f8117f84042b3.jpg',
            ],
             [
                'id' => 15,
                'title' => 'WandaVision',
                'description' => 'Viviendo vidas suburbanas idealizadas, los seres con superpoderes Wanda y Vision comienzan a sospechar que no todo es lo que parece.',
                'genre' => 'Action, Comedy, Drama, Fantasy, Mystery, Sci-Fi',
                'release_year' => 2021,
                'seasons' => 1,
                'rating' => 7.9,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNI3YeUr6PJcap2j2HETdqcyLSVtf1W8g-gQ&s',
            ],
            [
                'id' => 16,
                'title' => 'The Falcon and the Winter Soldier',
                'description' => 'Después de los eventos de "Avengers: Endgame", Sam Wilson/Falcon y Bucky Barnes/Winter Soldier se unen en una aventura global que pone a prueba sus habilidades y su paciencia.',
                'genre' => 'Action, Adventure, Drama, Sci-Fi',
                'release_year' => 2021,
                'seasons' => 1,
                'rating' => 7.2,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/en/9/9a/The_Falcon_and_the_Winter_Soldier_logo.png',
            ],
            [
                'id' => 17,
                'title' => 'El juego del calamar',
                'description' => 'Cientos de jugadores con problemas de dinero aceptan una extraña invitación a competir en juegos infantiles. Dentro, les espera un premio tentador con apuestas mortalmente altas.',
                'genre' => 'Action, Drama, Mystery, Sci-Fi, Thriller',
                'release_year' => 2021,
                'seasons' => 2,
                'rating' => 8.0,
                'image_url' => 'https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/102021/el_juego_del_calamar.png?wIRMtbaeI0kDQsNOxhNtyd91B2PGOuLs&itok=98340yWk',
            ],
            [
                'id' => 18,
                'title' => 'La casa de papel',
                'description' => 'Un grupo inusual de ladrones intenta llevar a cabo el robo más perfecto de la historia de España: robar 2.400 millones de euros de la Fábrica Nacional de Moneda y Timbre.',
                'genre' => 'Action, Crime, Drama, Mystery, Thriller',
                'release_year' => 2017,
                'seasons' => 5,
                'rating' => 8.2,
                'image_url' => 'https://m.media-amazon.com/images/M/MV5BZDI0Zjk2NjMtOGRhMy00YzkyLWIwMzgtYmNiZDczM2IzOTAzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
            ],
            [
                'id' => 19,
                'title' => 'The Witcher',
                'description' => 'Geralt de Rivia, un solitario cazador de monstruos, lucha por encontrar su lugar en un mundo donde las personas a menudo demuestran ser más malvadas que las bestias.',
                'genre' => 'Action, Adventure, Drama, Fantasy, Mystery',
                'release_year' => 2019,
                'seasons' => 3,
                'rating' => 8.0,
                'image_url' => 'https://i.pinimg.com/736x/00/60/22/0060225a82c0d9b311f21803bf477e45.jpg',
            ],
             [
                'id' => 20,
                'title' => 'Cobra Kai',
                'description' => 'Décadas después de su pelea original, un ahora exitoso Daniel LaRusso y un venido a menos Johnny Lawrence vuelven a cruzar sus caminos cuando Johnny reabre el dojo Cobra Kai.',
                'genre' => 'Action, Comedy, Drama, Sport',
                'release_year' => 2018,
                'seasons' => 6,
                'rating' => 8.5,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP1Bo259nUWlXEGtLi_sC-4zkal4sm6kUDlQ&s',
            ],
             [
                'id' => 21,
                'title' => 'The Umbrella Academy',
                'description' => 'Una disfuncional familia de hermanos adoptados con superpoderes se reúne para resolver el misterio de la muerte de su padre y la amenaza de un apocalipsis inminente.',
                'genre' => 'Action, Adventure, Comedy, Drama, Fantasy, Sci-Fi',
                'release_year' => 2019,
                'seasons' => 4,
                'rating' => 7.9,
                'image_url' => 'https://media.a24.com/p/c3d314055e0dd87187f75d97c68b4cf3/adjuntos/296/imagenes/008/753/0008753325/1200x675/smart/netflix-umbrellajpg.jpg',
            ],
            [
                'id' => 22,
                'title' => 'Peaky Blinders',
                'description' => 'Una épica historia de gánsteres ambientada en Birmingham, Inglaterra, en el año 1919.',
                'genre' => 'Crime, Drama',
                'release_year' => 2013,
                'seasons' => 6,
                'rating' => 8.8,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/1/13/Peaky_Blinders_Logo.png',
            ],
             [
                'id' => 23,
                'title' => 'Lucifer',
                'description' => 'Como el ángel original, Lucifer Morningstar se ha aburrido e infelicitado como el Señor del Infierno. Renuncia y se muda a Los Ángeles y abre un club nocturno.',
                'genre' => 'Crime, Drama, Fantasy',
                'release_year' => 2016,
                'seasons' => 6,
                'rating' => 8.1,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Lucifer_Tv_Serie_logo.svg/1200px-Lucifer_Tv_Serie_logo.svg.png',
            ],
            [
                'id' => 24,
                'title' => 'The Boys presenta: Diabolical',
                'description' => 'Una serie de antología animada ambientada en el universo de The Boys.',
                'genre' => 'Animation, Action, Comedy, Crime, Fantasy, Horror, Sci-Fi',
                'release_year' => 2022,
                'seasons' => 1,
                'rating' => 7.3,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0xmfe8zV4TqljNW2NqSxlh6gd2jn9tbGBig&s',
            ],
             [
                'id' => 25,
                'title' => 'Ozark',
                'description' => 'Un asesor financiero arrastra a su familia de Chicago a los Ozarks de Misuri, donde debe lavar dinero para apaciguar a un cartel de drogas.',
                'genre' => 'Crime, Drama, Thriller',
                'release_year' => 2017,
                'seasons' => 4,
                'rating' => 8.5,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTduBAjjSd6E_MpmbRf8guFTw7GUGtIZkcokA&s',
            ],
             [
                'id' => 26,
                'title' => 'Gambito de reina',
                'description' => 'Huérfana a los nueve años, prodigiosa introvertida Beth Harmon descubre un asombroso talento para el ajedrez y comienza su camino al estrellato mientras lucha contra la adicción.',
                'genre' => 'Drama, Sport',
                'release_year' => 2020,
                'seasons' => 1,
                'rating' => 8.5,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8j9H6i2v215WHI9J0B6l7l5TgoIiJletsGw&s',
            ],
            [
                'id' => 27,
                'title' => 'The Office (US)',
                'description' => 'Un falso documental sobre un grupo de oficinistas típicos, donde la jornada laboral consiste en choques de egos, comportamiento inapropiado y tedio.',
                'genre' => 'Comedy',
                'release_year' => 2005,
                'seasons' => 9,
                'rating' => 9.0,
                'image_url' => 'https://1000marcas.net/wp-content/uploads/2025/02/The-Office-Logo.jpg',
            ],
             [
                'id' => 28,
                'title' => 'Parks and Recreation',
                'description' => 'Las absurdas payasadas de los funcionarios públicos de un pueblo de Indiana mientras persiguen varios proyectos para hacer de su ciudad un lugar mejor.',
                'genre' => 'Comedy',
                'release_year' => 2009,
                'seasons' => 7,
                'rating' => 8.6,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnPz_BkPM1a4O1h4OPw8YomDMAbvZvQO1qLA&s',
            ],
             [
                'id' => 29,
                'title' => 'The Big Bang Theory',
                'description' => 'Una mujer que se muda a un apartamento al otro lado del pasillo de dos físicos brillantes pero socialmente torpes les muestra lo poco que saben sobre la vida fuera del laboratorio.',
                'genre' => 'Comedy, Romance, Sci-Fi',
                'release_year' => 2007,
                'seasons' => 12,
                'rating' => 8.1,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/en/7/7b/The_Big_Bang_Theory_%28Official_Title_Card%29.png',
            ],
             [
                'id' => 30,
                'title' => 'Friends: La Reunión',
                'description' => 'El elenco de Friends se reúne para una noche de diversión sin guion para celebrar la querida serie.',
                'genre' => 'Comedy, Reality-TV',
                'release_year' => 2021,
                'seasons' => 1,
                'rating' => 8.0,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn9su0uKIntIPLZSKGROc879qFy3EuQl51rQ&s',
            ],
            [
                'id' => 31,
                'title' => 'House M.D.',
                'description' => 'Dirigido por el Dr. Gregory House, un genio médico poco convencional y misántropo, un equipo de diagnosticadores resuelve casos desconcertantes en el Hospital Universitario Princeton-Plainsboro.',
                'genre' => 'Drama, Mystery',
                'release_year' => 2004,
                'seasons' => 8,
                'rating' => 8.7,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5urF7xFBaQNOkhYKp3UXJvw6mvC9s2Df_Pw&s',
            ],
             [
                'id' => 32,
                'title' => 'Lost',
                'description' => 'Los supervivientes de un accidente aéreo se ven obligados a trabajar juntos para sobrevivir en una isla tropical aparentemente desierta.',
                'genre' => 'Adventure, Drama, Fantasy, Mystery, Sci-Fi, Thriller',
                'release_year' => 2004,
                'seasons' => 6,
                'rating' => 8.3,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Lost_letters.jpg',
            ],
             [
                'id' => 33,
                'title' => 'Dexter',
                'description' => 'De día, el apacible Dexter es un analista de salpicaduras de sangre para la policía de Miami Metro. Pero de noche, es un asesino en serie que solo se dirige a otros asesinos.',
                'genre' => 'Crime, Drama, Mystery, Thriller',
                'release_year' => 2006,
                'seasons' => 8,
                'rating' => 8.6,
                'image_url' => 'https://i.pinimg.com/736x/6a/fc/28/6afc282f06b4ddbb043e530ad4408627.jpg',
            ],
             [
                'id' => 34,
                'title' => 'Prison Break',
                'description' => 'Un ingeniero estructural se interna en una prisión que ayudó a diseñar, para escapar a su hermano falsamente acusado.',
                'genre' => 'Action, Crime, Drama, Mystery, Thriller',
                'release_year' => 2005,
                'seasons' => 5,
                'rating' => 8.3,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-VQJDq05DOXb5CLo7R8iKwpSccjf6C6EtRg&s',
            ],
             [
                'id' => 35,
                'title' => 'Better Call Saul',
                'description' => 'Las pruebas y tribulaciones del abogado criminalista Jimmy McGill en los años previos a su fatídico encuentro con Walter White y Jesse Pinkman.',
                'genre' => 'Crime, Drama',
                'release_year' => 2015,
                'seasons' => 6,
                'rating' => 8.8,
                'image_url' => 'https://i.ytimg.com/vi/j9wtDQ2crEI/maxresdefault.jpg',
            ],
            [
                'id' => 36,
                'title' => 'Dark',
                'description' => 'Una familia alemana se ve envuelta en un misterio que abarca cuatro generaciones y revela una conspiración que conecta el pasado con el presente.',
                'genre' => 'Crime, Drama, Mystery, Sci-Fi, Thriller',
                'release_year' => 2017,
                'seasons' => 3,
                'rating' => 8.7,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwwlfzrNA316N8EVOlnTT0DFABCqUXl9Gtmg&s',
            ],
            [
                'id' => 37,
                'title' => 'Westworld',
                'description' => 'En un parque temático futurista, los androides que viven en un mundo del salvaje oeste comienzan a cuestionar su realidad.',
                'genre' => 'Drama, Mystery, Sci-Fi, Western',
                'release_year' => 2016,
                'seasons' => 4,
                'rating' => 8.5,
                'image_url' => 'https://m.media-amazon.com/images/I/71-ZbylGYYL._UF1000,1000_QL80_.jpg',
            ],
            [
                'id' => 38,
                'title' => 'The Handmaid\'s Tale',
                'description' => 'En una distopía donde la fertilidad es un recurso escaso, una mujer lucha por sobrevivir en una sociedad totalitaria.',
                'genre' => 'Drama, Sci-Fi, Thriller',
                'release_year' => 2017,
                'seasons' => 5,
                'rating' => 8.4,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu3lYAXoWTq_n_2lcFoScbzLxum0BQNCRDvQ&s',
            ],
            [
                'id' => 39,
                'title' => 'The Good Place',
                'description' => 'Una mujer que ha vivido una vida egoísta se despierta en el cielo y debe aprender a ser una mejor persona.',
                'genre' => 'Comedy, Drama, Fantasy',
                'release_year' => 2016,
                'seasons' => 4,
                'rating' => 8.2,
                'image_url' => 'https://img.nbc.com/files/images/2019/8/15/TheGoodPlace_S4-Logo-1920x1080.jpg',
            ],
            [
                'id' => 40,
                'title' => 'Mindhunter',
                'description' => 'Dos agentes del FBI entrevistan a asesinos en serie encarcelados para entender cómo piensan y resolver casos en curso.',
                'genre' => 'Crime, Drama, Thriller',
                'release_year' => 2017,
                'seasons' => 2,
                'rating' => 8.6,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTktbO9m5Q2Nz93Gitka31G8rwdq6OKrYJxTg&s',
            ],
            [
                'id' => 41,
                'title' => 'The Expanse',
                'description' => 'En un futuro donde la humanidad ha colonizado el sistema solar, un detective y un capitán de nave espacial investigan un caso que podría desencadenar una guerra interplanetaria.',
                'genre' => 'Drama, Mystery, Sci-Fi',
                'release_year' => 2015,
                'seasons' => 6,
                'rating' => 8.5,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST67MHQcDvbn5i09vxuRfCEgfxeLCKJFocCw&s',
            ],
            [
                'id' => 42,
                'title' => 'The Good Doctor',
                'description' => 'Un joven cirujano con autismo y síndrome de savant es contratado en un prestigioso hospital, donde su genio médico y su humanidad desafían las expectativas.',
                'genre' => 'Drama, Medical',
                'release_year' => 2017,
                'seasons' => 6,
                'rating' => 8.1,
                'image_url' => 'https://m.media-amazon.com/images/S/pv-target-images/407e66050936f9b996ea97dff072c22606ded1e5e53bb18ad9b4678ee68b1d93.jpg',
            ],
            [
                'id' => 43,
                'title' => 'The Marvelous Mrs. Maisel',
                'description' => 'Una ama de casa de los años 50 descubre que tiene un talento especial para la comedia stand-up y persigue su sueño de convertirse en comediante profesional.',
                'genre' => 'Comedy, Drama',
                'release_year' => 2017,
                'seasons' => 5,
                'rating' => 8.7,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK4jJKRlrNS292_tZKVz88spda2XGxG7gSQQ&s',
            ],
            [
                'id' => 44,
                'title' => 'The Haunting of Hill House',
                'description' => 'Una familia que creció en la famosa casa embrujada se ve obligada a enfrentar sus miedos del pasado cuando regresan a la mansión.',
                'genre' => 'Drama, Horror, Mystery, Thriller',
                'release_year' => 2018,
                'seasons' => 1,
                'rating' => 8.6,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvy02-1Nv1jNwaOE7r_VMRvB3Up9lAheHfPw&s',
            ],
            [
                'id' => 45,
                'title' => 'The Man in the High Castle',
                'description' => 'En una realidad alternativa donde los nazis ganaron la Segunda Guerra Mundial, una joven descubre una película que muestra un mundo diferente.',
                'genre' => 'Drama, Sci-Fi, Thriller',
                'release_year' => 2015,
                'seasons' => 4,
                'rating' => 8.0,
                'image_url' => 'https://www.artofthetitle.com/assets/resized/sm/upload/cs/bu/nj/34/mihc_trailer_c-0-870-0-0.jpg?k=1bcafdc71d',
            ],
            [
                'id' => 46,
                'title' => 'The Leftovers',
                'description' => 'Tres años después de que el 2% de la población mundial desapareciera sin explicación, una ciudad intenta seguir adelante.',
                'genre' => 'Drama, Fantasy, Mystery',
                'release_year' => 2014,
                'seasons' => 3,
                'rating' => 8.3,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/en/3/39/LeftoversS2Logo.jpg',
            ],
            [
                'id' => 47,
                'title' => 'The Americans',
                'description' => 'Durante la Guerra Fría, dos espías soviéticos se hacen pasar por una pareja estadounidense normal en los suburbios de Washington D.C.',
                'genre' => 'Crime, Drama, Thriller',
                'release_year' => 2013,
                'seasons' => 6,
                'rating' => 8.4,
                'image_url' => 'https://m.media-amazon.com/images/S/pv-target-images/b96cde446262f1244546a9b1c3177ada8b8cc4fea7c317f18d29c66e78ee3ab5.jpg',
            ],
            [
                'id' => 48,
                'title' => 'The Night Of',
                'description' => 'Un joven pakistaní-estadounidense es acusado de un asesinato que no recuerda haber cometido.',
                'genre' => 'Crime, Drama, Mystery, Thriller',
                'release_year' => 2016,
                'seasons' => 1,
                'rating' => 8.5,
                'image_url' => 'https://images.cdn.prd.api.discomax.com/2023/04/20/cb5615f2-61df-3d40-8fc6-2699b39c3264.jpeg?f=jpg&q=75&w=1280&w=1200',
            ],
            [
                'id' => 49,
                'title' => 'The Young Pope',
                'description' => 'La historia del primer Papa estadounidense, un hombre joven y carismático que desafía las tradiciones del Vaticano.',
                'genre' => 'Drama',
                'release_year' => 2016,
                'seasons' => 2,
                'rating' => 8.2,
                'image_url' => 'https://images.cdn.prd.api.discomax.com/2023/05/21/3a8e4563-1d1c-3995-a946-cbc293dfd4c3.jpeg?f=jpg&q=75&w=1280&w=1200',
            ],
            [
                'id' => 50,
                'title' => 'The Night Manager',
                'description' => 'Un ex soldado británico es reclutado por una agencia de inteligencia para infiltrarse en el círculo íntimo de un traficante de armas internacional.',
                'genre' => 'Action, Crime, Drama, Thriller',
                'release_year' => 2016,
                'seasons' => 1,
                'rating' => 8.1,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCN1zCvLOPcGBN8FknDpTcJDXbSCXi1DD_kw&s',
            ],
            [
                'id' => 51,
                'title' => 'The Man Who Fell to Earth',
                'description' => 'Un extraterrestre llega a la Tierra en busca de agua para su planeta natal, pero se ve envuelto en los problemas de la humanidad.',
                'genre' => 'Drama, Sci-Fi',
                'release_year' => 2022,
                'seasons' => 1,
                'rating' => 7.5,
                'image_url' => 'https://m.media-amazon.com/images/S/pv-target-images/370cbf1d6060c09e00a1dec2a91ca5d9c7199bf6ff9fea050a91a523e49738dc.jpg',
            ],
            [
                'id' => 52,
                'title' => 'The Peripheral',
                'description' => 'Una joven descubre una conexión con una realidad alternativa que podría cambiar el futuro de la humanidad.',
                'genre' => 'Action, Drama, Mystery, Sci-Fi, Thriller',
                'release_year' => 2022,
                'seasons' => 1,
                'rating' => 7.6,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCY3ZQ48Gp_wvFXr_UsHvbfV3L5kS-tIeXmQ&s',
            ],
            [
                'id' => 53,
                'title' => 'The Sandman',
                'description' => 'Cuando Morfeo, el señor de los sueños, es capturado y encarcelado durante un siglo, su ausencia desencadena una serie de eventos que afectan tanto al mundo de los sueños como al de los humanos.',
                'genre' => 'Drama, Fantasy, Horror',
                'release_year' => 2022,
                'seasons' => 1,
                'rating' => 7.7,
                'image_url' => 'https://64.media.tumblr.com/d2647561f4067e22488fcbbd52283868/b5e32422e8eba5b4-d1/s1280x1920/7caac039d7042db1de77f3d1630dbc5234683a05.png',
            ],
            [
                'id' => 54,
                'title' => 'The Last of Us Part II',
                'description' => 'En un mundo post-apocalíptico, un hombre endurecido y una joven de 14 años deben sobrevivir mientras viajan a través de un Estados Unidos devastado.',
                'genre' => 'Action, Adventure, Drama, Horror, Sci-Fi, Thriller',
                'release_year' => 2023,
                'seasons' => 1,
                'rating' => 8.8,
                'image_url' => 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2025/03/nuevo-poster-last-us-temporada-2-4306104.jpg?tf=3840x',
            ],
            [
                'id' => 55,
                'title' => 'The Bear',
                'description' => 'Un chef de alta cocina regresa a Chicago para dirigir el restaurante de sándwiches de su difunto hermano.',
                'genre' => 'Comedy, Drama',
                'release_year' => 2022,
                'seasons' => 2,
                'rating' => 8.6,
                'image_url' => 'https://media.themoviedb.org/t/p/w780/csnJf7QslLWl2oekdm3mO3INFiq.jpg',
            ]
        ];
        return $series;
    }

    /**
     * Muestra la lista de todas las series
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $series = $this->getSeriesData();
        return view('series.index', ['series' => $series]);
    }

    /**
     * Muestra los detalles de una serie específica
     * @param int $id ID de la serie
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $allSeries = $this->getSeriesData();
        $series = null;
        foreach ($allSeries as $item) {
            if ($item['id'] == $id) {
                $series = $item;
                break;
            }
        }

        if (!$series) {
            abort(404);
        }

        return view('series.show', ['series' => $series]);
    }
}
